$('.one').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    autoplay:true,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
   
    responsive:{
        0:{
            items:1
        },
        300:{
            items:2
        },
        700:{
            items:4
        },
        1000:{
            items:6
        }
    }
})


$('.two').owlCarousel({
    rtl:true,
    loop:true,
    margin:15,
    nav:true,
    autoplay:true,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
    dots:false,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:4
        },
        1000:{
            items:5
        }
    }
})